### ISSUE TITLE
Raspbian compatible

### ISSUE THREAD

**Issue by vay3t** [Hackplayers/4nonimizer#1]
I tried it on raspbian 8 and apparently works well. I made some minor modifications because I can not down the interface where I am connected. "icanhazip.com" have problems viewing the ip spoofed. for that I suggest change for "ipecho.net/plain". isnt perfect, but it works.
# How to install in Raspbian

```
git clone https://github.com/Hackplayers/4nonimizer
cd 4nonimizer
curl -s https://gist.githubusercontent.com/vay3t/b02f77699538aafcbd73e31af9301fc4/raw/9ebb3fa198b6202a76ebf0c6d5fae27306aa6b0e/4nonimizer > 4nonimizer
sudo ./4nonimizer install
sudo 4nonimizer start
```
#### Sometimes I have problems with openvpn

```
[+] There is a problem starting openvpn. Please, check nohup.out for details

tail: no se puede abrir «/opt/4nonimizer/vpn/4nonimizer/nohup.out» para lectura: No existe el fichero o el directorio
```

**Comment by charly837** [comment]
ok, thanks for report this issue. 
We now tried test on rasberry before the commit changes for test the complete compatibility and perform tests

**Comment by charly837** [comment]
4nonimizer now have compatibility with Raspbian, thanks , I close the issue

**Comment by amreos** [comment]
[+] There is a problem starting openvpn. Please, check nohup.out for details

Thu Jul 13 01:21:02 2017 TCP_CLIENT link local: (not bound)
Thu Jul 13 01:21:02 2017 TCP_CLIENT link remote: [AF_INET]176.126.237.217:80
Thu Jul 13 01:21:02 2017 TLS: Initial packet from [AF_INET]176.126.237.217:80, sid=77f0a2d2 6e6a06a4
Thu Jul 13 01:21:04 2017 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Thu Jul 13 01:21:04 2017 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Thu Jul 13 01:21:08 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 1024 bit RSA
Thu Jul 13 01:21:08 2017 [vpnbook.com] Peer Connection Initiated with [AF_INET]176.126.237.217:80
Thu Jul 13 01:21:10 2017 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Thu Jul 13 01:21:11 2017 AUTH: Received control message: AUTH_FAILED
Thu Jul 13 01:21:11 2017 SIGTERM[soft,auth-failure] received, process exiting
Thu Jul 13 02:02:28 2017 WARNING: file 'pass.txt' is group or others accessible
Thu Jul 13 02:02:28 2017 OpenVPN 2.4.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 30 2017
Thu Jul 13 02:02:28 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Thu Jul 13 02:02:28 2017 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Thu Jul 13 02:02:28 2017 NOTE: --fast-io is disabled since we are not using UDP
Thu Jul 13 02:02:28 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]178.162.193.233:80
Thu Jul 13 02:02:28 2017 Socket Buffers: R=[87380->87380] S=[16384->16384]
Thu Jul 13 02:02:28 2017 Attempting to establish TCP connection with [AF_INET]178.162.193.233:80 [nonblock]
Thu Jul 13 02:02:29 2017 TCP connection established with [AF_INET]178.162.193.233:80
Thu Jul 13 02:02:29 2017 TCP_CLIENT link local: (not bound)
Thu Jul 13 02:02:29 2017 TCP_CLIENT link remote: [AF_INET]178.162.193.233:80
Thu Jul 13 02:02:29 2017 TLS: Initial packet from [AF_INET]178.162.193.233:80, sid=4c3ff9e3 22540d5d
Thu Jul 13 02:02:29 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Jul 13 02:02:30 2017 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Thu Jul 13 02:02:30 2017 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Thu Jul 13 02:02:34 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 1024 bit RSA
Thu Jul 13 02:02:34 2017 [vpnbook.com] Peer Connection Initiated with [AF_INET]178.162.193.233:80
Thu Jul 13 02:02:36 2017 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Thu Jul 13 02:02:36 2017 AUTH: Received control message: AUTH_FAILED
Thu Jul 13 02:02:36 2017 SIGTERM[soft,auth-failure] received, process exiting
