### ISSUE TITLE
there is a problem starting ovpn check nogup.out  for details

### ISSUE THREAD

**Issue by glaucobonomo** [Hackplayers/4nonimizer#18]
i installed 4nonimizer and i started it, i ried change different providers, i updated it, but i still get this type of error when i tri to start...it was the best vpn i could find, pleas let's fix this 
 Starting 4nonimizer to hide your real IP...

..............................

[+] There is a problem starting openvpn. Please, check nohup.out for details

Sat May 27 14:45:42 2017 Exiting due to fatal error
Sat May 27 14:47:59 2017 WARNING: file 'pass.txt' is group or others accessible
Sat May 27 14:47:59 2017 OpenVPN 2.4.0 [git:master/de39933a5c67a449+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 11 2017
Sat May 27 14:47:59 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Sat May 27 14:49:29 2017 ERROR: Failed retrieving username or password
Sat May 27 14:49:29 2017 Exiting due to fatal error
Sat May 27 17:20:45 2017 WARNING: file 'pass.txt' is group or others accessible
Sat May 27 17:20:45 2017 OpenVPN 2.4.0 [git:master/de39933a5c67a449+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 11 2017
Sat May 27 17:20:45 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Sat May 27 17:21:12 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]154.70.152.210:553
Sat May 27 17:21:12 2017 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sat May 27 17:21:12 2017 UDP link local: (not bound)
Sat May 27 17:21:12 2017 UDP link remote: [AF_INET]154.70.152.210:553
Sat May 27 17:21:13 2017 TLS: Initial packet from [AF_INET]154.70.152.210:553, sid=69e777bd bd3029fc
Sat May 27 17:21:13 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sat May 27 17:21:15 2017 VERIFY OK: depth=1, C=UK, ST=London, L=London, O=Privax Ltd, OU=HMA Pro VPN, CN=hidemyass.com, emailAddress=info@privax.com
Sat May 27 17:21:15 2017 VERIFY OK: nsCertType=SERVER
Sat May 27 17:21:15 2017 VERIFY OK: depth=0, C=UK, ST=London, L=London, O=Privax Ltd, OU=HMA Pro VPN, CN=server, emailAddress=info@privax.com
Sat May 27 17:21:28 2017 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558'
Sat May 27 17:21:28 2017 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
Sat May 27 17:21:28 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
Sat May 27 17:21:28 2017 [server] Peer Connection Initiated with [AF_INET]154.70.152.210:553
Sat May 27 17:21:29 2017 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Sat May 27 17:21:30 2017 AUTH: Received control message: AUTH_FAILED
Sat May 27 17:21:30 2017 SIGTERM[soft,auth-failure] received, process exiting
Options error: I'm trying to parse "/opt/4nonimizer/vpn/tunnelbear/TunnelBear" as an --option parameter but I don't see a leading '--'
Use --help for more information.
Sun May 28 11:47:29 2017 WARNING: file 'pass.txt' is group or others accessible
Sun May 28 11:47:29 2017 OpenVPN 2.4.0 [git:master/de39933a5c67a449+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 11 2017
Sun May 28 11:47:29 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08

**Comment by glaucobonomo** [comment]
4nonimizer Version: 1.07-beta

**Comment by vmotos** [comment]
Hello, 

the error message is "AUTH_FAILED". Do you have valid credentials for TunnelBear?
Please, try again using a free VPN (eg. vpnbook) and give us feedback.

Rgds,

**Comment by glaucobonomo** [comment]
i just installed parrot 3.6 and i installe 4nonimizer, all suggested packages, i started it, and this is the output

[+] Starting 4nonimizer to hide your real IP...

..............................








[+] There is a problem starting openvpn. Please, check nohup.out for details

Wed May 31 14:12:25 2017 WARNING: file 'pass.txt' is group or others accessible
Wed May 31 14:12:25 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed May 31 14:12:25 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08

**Comment by glaucobonomo** [comment]
i left default settings so should be vpnbook provider

**Comment by glaucobonomo** [comment]
any news?

**Comment by vmotos** [comment]
What's the real problem? Could you copy all log message? Could you execute 'openvpn file.ovpn' in order to check the output too?

**Comment by glaucobonomo** [comment]
this is openvpn output...
openvpn --config vpnbook-euro1-tcp80.ovpn
Mon Jun  5 17:52:51 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Mon Jun  5 17:52:51 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Enter Auth Username: vpnbook
Enter Auth Password: *******
Mon Jun  5 17:52:59 2017 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Mon Jun  5 17:52:59 2017 NOTE: --fast-io is disabled since we are not using UDP
Mon Jun  5 17:52:59 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]176.126.237.217:80
Mon Jun  5 17:52:59 2017 Socket Buffers: R=[87380->87380] S=[16384->16384]
Mon Jun  5 17:52:59 2017 Attempting to establish TCP connection with [AF_INET]176.126.237.217:80 [nonblock]
Mon Jun  5 17:53:00 2017 TCP connection established with [AF_INET]176.126.237.217:80
Mon Jun  5 17:53:00 2017 TCP_CLIENT link local: (not bound)
Mon Jun  5 17:53:00 2017 TCP_CLIENT link remote: [AF_INET]176.126.237.217:80
Mon Jun  5 17:53:00 2017 TLS: Initial packet from [AF_INET]176.126.237.217:80, sid=3bcf067d 144bdbde
Mon Jun  5 17:53:00 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Jun  5 17:53:01 2017 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Mon Jun  5 17:53:01 2017 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Mon Jun  5 17:53:02 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 1024 bit RSA
Mon Jun  5 17:53:02 2017 [vpnbook.com] Peer Connection Initiated with [AF_INET]176.126.237.217:80
Mon Jun  5 17:53:03 2017 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Mon Jun  5 17:53:03 2017 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS  89.233.43.71,dhcp-option DNS  91.239.100.100,route 10.12.0.1,topology net30,ping 5,ping-restart 30,ifconfig 10.12.0.142 10.12.0.141'
Mon Jun  5 17:53:03 2017 OPTIONS IMPORT: timers and/or timeouts modified
Mon Jun  5 17:53:03 2017 OPTIONS IMPORT: --ifconfig/up options modified
Mon Jun  5 17:53:03 2017 OPTIONS IMPORT: route options modified
Mon Jun  5 17:53:03 2017 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Mon Jun  5 17:53:03 2017 Data Channel Encrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Mon Jun  5 17:53:03 2017 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Jun  5 17:53:03 2017 Data Channel Decrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
Mon Jun  5 17:53:03 2017 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Jun  5 17:53:03 2017 ROUTE_GATEWAY 192.168.1.254/255.255.255.0 IFACE=wlan0 HWADDR=c4:17:fe:b3:1d:ff
Mon Jun  5 17:53:03 2017 TUN/TAP device tun3 opened
Mon Jun  5 17:53:03 2017 TUN/TAP TX queue length set to 100
Mon Jun  5 17:53:03 2017 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Mon Jun  5 17:53:03 2017 /sbin/ip link set dev tun3 up mtu 1500
Mon Jun  5 17:53:03 2017 /sbin/ip addr add dev tun3 local 10.12.0.142 peer 10.12.0.141
Mon Jun  5 17:53:05 2017 /sbin/ip route add 176.126.237.217/32 via 192.168.1.254
Mon Jun  5 17:53:05 2017 /sbin/ip route add 0.0.0.0/1 via 10.12.0.141
Mon Jun  5 17:53:05 2017 /sbin/ip route add 128.0.0.0/1 via 10.12.0.141
Mon Jun  5 17:53:05 2017 /sbin/ip route add 10.12.0.1/32 via 10.12.0.141
Mon Jun  5 17:53:05 2017 Initialization Sequence Completed


instead this is 4nonimizer using vpnbook
[+] Your current IP is ...


[+] Starting 4nonimizer to hide your real IP...

..............................








[+] There is a problem starting openvpn. Please, check nohup.out for details

Wed May 31 14:12:25 2017 WARNING: file 'pass.txt' is group or others accessible
Wed May 31 14:12:25 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed May 31 14:12:25 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Wed May 31 14:13:55 2017 ERROR: Failed retrieving username or password
Wed May 31 14:13:55 2017 Exiting due to fatal error
Mon Jun  5 17:54:53 2017 WARNING: file 'pass.txt' is group or others accessible
Mon Jun  5 17:54:53 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Mon Jun  5 17:54:53 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08

**Comment by vmotos** [comment]
It seems that there is a problem downloading the vpnbook's credentials. Please, visit https://www.vpnbook.com/#openvpn and copy user and password into ./vpn/vpnbook/pass.txt.

Also, in order to debug the issue if you want execute the script 4nonimizer/vpn/vpnbook/vpn-get-pass.sh and see the result (feedback pls).

Regards

**Comment by glaucobonomo** [comment]
this is the output after i pasted vpnbook password in pass.txt

[+] There is a problem starting openvpn. Please, check nohup.out for details

Wed Jun  7 10:48:37 2017 WARNING: file 'pass.txt' is group or others accessible
Wed Jun  7 10:48:37 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed Jun  7 10:48:37 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Wed Jun  7 10:50:08 2017 ERROR: Failed retrieving username or password
Wed Jun  7 10:50:08 2017 Exiting due to fatal error
Wed Jun  7 10:50:17 2017 WARNING: file 'pass.txt' is group or others accessible
Wed Jun  7 10:50:17 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed Jun  7 10:50:17 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Wed Jun  7 10:51:04 2017 WARNING: file 'pass.txt' is group or others accessible
Wed Jun  7 10:51:04 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed Jun  7 10:51:04 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Wed Jun  7 10:51:47 2017 ERROR: Failed retrieving username or password
Wed Jun  7 10:51:47 2017 Exiting due to fatal error
Wed Jun  7 10:54:16 2017 WARNING: file 'pass.txt' is group or others accessible
Wed Jun  7 10:54:16 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed Jun  7 10:54:16 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08

after executing script vpn-get-pass.sh in vpnbook

command 4nonimizer start 

[+] There is a problem starting openvpn. Please, check nohup.out for details

Wed Jun  7 10:48:37 2017 WARNING: file 'pass.txt' is group or others accessible
Wed Jun  7 10:48:37 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed Jun  7 10:48:37 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Wed Jun  7 10:50:08 2017 ERROR: Failed retrieving username or password
Wed Jun  7 10:50:08 2017 Exiting due to fatal error
Wed Jun  7 10:50:17 2017 WARNING: file 'pass.txt' is group or others accessible
Wed Jun  7 10:50:17 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed Jun  7 10:50:17 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Wed Jun  7 10:51:04 2017 WARNING: file 'pass.txt' is group or others accessible
Wed Jun  7 10:51:04 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed Jun  7 10:51:04 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Wed Jun  7 10:51:47 2017 ERROR: Failed retrieving username or password
Wed Jun  7 10:51:47 2017 Exiting due to fatal error
Wed Jun  7 10:54:16 2017 WARNING: file 'pass.txt' is group or others accessible
Wed Jun  7 10:54:16 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed Jun  7 10:54:16 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Wed Jun  7 10:55:46 2017 ERROR: Failed retrieving username or password
Wed Jun  7 10:55:46 2017 Exiting due to fatal error
Wed Jun  7 10:56:08 2017 WARNING: file 'pass.txt' is group or others accessible
Wed Jun  7 10:56:08 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed Jun  7 10:56:08 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Wed Jun  7 10:56:21 2017 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Wed Jun  7 10:56:21 2017 NOTE: --fast-io is disabled since we are not using UDP
Wed Jun  7 10:56:21 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]178.162.193.233:80
Wed Jun  7 10:56:21 2017 Socket Buffers: R=[87380->87380] S=[16384->16384]
Wed Jun  7 10:56:21 2017 Attempting to establish TCP connection with [AF_INET]178.162.193.233:80 [nonblock]
Wed Jun  7 10:57:02 2017 WARNING: file 'pass.txt' is group or others accessible
Wed Jun  7 10:57:02 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Wed Jun  7 10:57:02 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08

**Comment by glaucobonomo** [comment]
┌─[✗]─[root@parrot]─[/home/username/4nonimizer/vpn/vpnbook]
└──╼ #./vpn-get-pass.sh 
┌─[root@parrot]─[/home/username/4nonimizer/vpn/vpnbook]
└──╼ #

**Comment by vmotos** [comment]
I think I've just detect the problem. VPNbook had changed the web access to HTTPS (HTTP has a redirect) and for that reason the script could not obtain the credentials in an automatic way.
I've fixed it. Please update the app and test again.

**Comment by glaucobonomo** [comment]
ok, i'll try now

**Comment by glaucobonomo** [comment]
it woooooorks!!!! you're awsome man, thank u soooo much, i fuckink love u man thanks ;)

**Comment by vmotos** [comment]
hahaha thanks to you. With your comments you help us to make a better tool for everybody. Best regards

**Comment by nishatmamun** [comment]
How to update the app? vmotos

**Comment by letorruella** [comment]
@sudobro ` 4nonimizer update_app`

**Comment by cadudib** [comment]
The problem is back :(

**Comment by wahyudibayuputra** [comment]
[+] There is a problem starting openvpn. Please, check nohup.out for details

Fri May 24 09:46:58 2019 ERROR: Failed retrieving username or password
Fri May 24 09:46:58 2019 Exiting due to fatal error
Fri May 24 09:48:27 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:48:27 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:48:27 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:49:57 2019 ERROR: Failed retrieving username or password
Fri May 24 09:49:57 2019 Exiting due to fatal error
Fri May 24 09:50:21 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:50:21 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:50:21 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:51:51 2019 ERROR: Failed retrieving username or password
Fri May 24 09:51:51 2019 Exiting due to fatal error
Fri May 24 09:54:48 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:54:48 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:54:48 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:56:18 2019 ERROR: Failed retrieving username or password
Fri May 24 09:56:18 2019 Exiting due to fatal error
Fri May 24 09:56:28 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:56:28 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:56:28 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:57:58 2019 ERROR: Failed retrieving username or password
Fri May 24 09:57:58 2019 Exiting due to fatal error
Fri May 24 09:58:41 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:58:41 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:58:41 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 10:00:11 2019 ERROR: Failed retrieving username or password
Fri May 24 10:00:11 2019 Exiting due to fatal error
Fri May 24 10:20:46 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 10:20:46 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 10:20:46 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10

help me plss, what is this problem ?

**Comment by DaniyalYaseen-ai** [comment]
I am having the same problem, can any please @vmotos help.

This is the output even after updating 4nonimizer.


[+] There is a problem starting openvpn. Please, check nohup.out for details

Wed Nov 13 13:04:33 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:04:33 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:04:33 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:06:03 2019 ERROR: Failed retrieving username or password
Wed Nov 13 13:06:03 2019 Exiting due to fatal error
Wed Nov 13 13:06:39 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:06:39 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:06:39 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:08:09 2019 ERROR: Failed retrieving username or password
Wed Nov 13 13:08:09 2019 Exiting due to fatal error
Wed Nov 13 13:08:32 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:08:32 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:08:32 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:10:02 2019 ERROR: Failed retrieving username or password
Wed Nov 13 13:10:02 2019 Exiting due to fatal error
Wed Nov 13 13:26:13 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:26:13 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:26:13 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:30:22 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:30:22 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:30:22 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10

root@kali:~/Desktop/4nonimizer#

**Comment by DaniyalYaseen-ai** [comment]
I am having the same problem, can any please @vmotos help.

This is the output even after updating 4nonimizer.


[+] There is a problem starting openvpn. Please, check nohup.out for details

Wed Nov 13 13:04:33 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:04:33 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:04:33 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:06:03 2019 ERROR: Failed retrieving username or password
Wed Nov 13 13:06:03 2019 Exiting due to fatal error
Wed Nov 13 13:06:39 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:06:39 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:06:39 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:08:09 2019 ERROR: Failed retrieving username or password
Wed Nov 13 13:08:09 2019 Exiting due to fatal error
Wed Nov 13 13:08:32 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:08:32 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:08:32 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:10:02 2019 ERROR: Failed retrieving username or password
Wed Nov 13 13:10:02 2019 Exiting due to fatal error
Wed Nov 13 13:26:13 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:26:13 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:26:13 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:30:22 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:30:22 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:30:22 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10

root@kali:~/Desktop/4nonimizer#

**Comment by DaniyalYaseen-ai** [comment]
Dear All,
Previous issue has been resolved but now I amgetting below mentioned error. When I run ./4nonimizer start , first it detects my real public IP then gives following output. Someone please help.

[+] There is a problem starting openvpn. Please, check nohup.out for details

Wed Nov 13 14:27:38 2019 Socket Buffers: R=[131072->131072] S=[16384->16384]
Wed Nov 13 14:27:38 2019 Attempting to establish TCP connection with [AF_INET]198.7.62.204:443 [nonblock]
Wed Nov 13 14:27:39 2019 TCP connection established with [AF_INET]198.7.62.204:443
Wed Nov 13 14:27:39 2019 TCP_CLIENT link local: (not bound)
Wed Nov 13 14:27:39 2019 TCP_CLIENT link remote: [AF_INET]198.7.62.204:443
Wed Nov 13 14:27:40 2019 WARNING: No server certificate verification method has been enabled. See http://openvpn.net/howto.html#mitm for more info.
Wed Nov 13 14:27:40 2019 NOTE: --fast-io is disabled since we are not using UDP
Wed Nov 13 14:27:40 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:40 2019 Socket Buffers: R=[131072->131072] S=[16384->16384]
Wed Nov 13 14:27:40 2019 Attempting to establish TCP connection with [AF_INET]198.7.58.147:443 [nonblock]
Wed Nov 13 14:27:41 2019 TCP connection established with [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:41 2019 TCP_CLIENT link local: (not bound)
Wed Nov 13 14:27:41 2019 TCP_CLIENT link remote: [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:42 2019 Connection reset, restarting [-1]
Wed Nov 13 14:27:42 2019 SIGUSR1[soft,connection-reset] received, process restarting
Wed Nov 13 14:27:42 2019 Restart pause, 80 second(s)
Wed Nov 13 14:27:44 2019 Connection reset, restarting [-1]
Wed Nov 13 14:27:44 2019 SIGUSR1[soft,connection-reset] received, process restarting
Wed Nov 13 14:27:44 2019 Restart pause, 5 second(s)
Wed Nov 13 14:27:49 2019 WARNING: No server certificate verification method has been enabled. See http://openvpn.net/howto.html#mitm for more info.
Wed Nov 13 14:27:49 2019 NOTE: --fast-io is disabled since we are not using UDP
Wed Nov 13 14:27:49 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:49 2019 Socket Buffers: R=[131072->131072] S=[16384->16384]
Wed Nov 13 14:27:49 2019 Attempting to establish TCP connection with [AF_INET]198.7.58.147:443 [nonblock]
Wed Nov 13 14:27:50 2019 TCP connection established with [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:50 2019 TCP_CLIENT link local: (not bound)
Wed Nov 13 14:27:50 2019 TCP_CLIENT link remote: [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:52 2019 Connection reset, restarting [-1]
Wed Nov 13 14:27:52 2019 SIGUSR1[soft,connection-reset] received, process restarting
Wed Nov 13 14:27:52 2019 Restart pause, 5 second(s)

**Comment by pasttt** [comment]
sed: can't read /opt/4nonimizer/vpn/vpnbook/*.ovpn: No such file or directory
ls: cannot access '/opt/4nonimizer/vpn/vpnbook/*.ovpn': No such file or directory


Plisss

**Comment by HonoreDeBalzac** [comment]
@glaucobonomo How did u fixed that problem men ? I updated the app , but the same issue pop up....pls help !

**Comment by anon1219420** [comment]
> @glaucobonomo How did u fixed that problem men ? I updated the app , but the same issue pop up....pls help !

Same did you find a fix?
