### ISSUE TITLE
NO CONNECT

### ISSUE THREAD

**Issue by BEYLERBEY** [Hackplayers/4nonimizer#20]
sorry guy,
i have this problem but i don't find  solution, don't understand.
Please can you help me?

[+] There is a problem starting openvpn. Please, check nohup.out for details

Sun Jun  4 13:23:43 2017 WARNING: file 'pass.txt' is group or others accessible
Sun Jun  4 13:23:43 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Sun Jun  4 13:23:43 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08
Sun Jun  4 13:23:49 2017 ERROR: Failed retrieving username or password
Sun Jun  4 13:23:49 2017 Exiting due to fatal error
Sun Jun  4 13:24:05 2017 WARNING: file 'pass.txt' is group or others accessible
Sun Jun  4 13:24:05 2017 OpenVPN 2.4.0 [git:master/d73f7253d939e293+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 22 2017
Sun Jun  4 13:24:05 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.08

**Comment by vmotos** [comment]
Hello, what VPN provider are you using? Do you have credentials and these are in pass.txt file?

**Comment by BEYLERBEY** [comment]
vpnbook
but the pass.txt is empty

**Comment by vmotos** [comment]
Ok, so that's the problem. Please, try to execute '4nonimizer update_vpns' or directly './vpn/vpnbook/vpn-get-pass.sh'. The credentials should download automatically (vpnbook is free :)

**Comment by vmotos** [comment]
The vpnbook provider had changed the web access (redirection to HTTPS) and we've fixed the corresponding script to download the credentials in an automatic way.

**Comment by BEYLERBEY** [comment]
And now what I must do? Uninstall and reinstall programm is better?

Paolo Di Sciorio

Il 11 giu 2017 22:27, "Vicente Motos" <notifications@github.com> ha scritto:

**Comment by vmotos** [comment]
Yes Paolo, reinstall the app. please

**Comment by BEYLERBEY** [comment]
hello brother, 
everithing is ok.
beautiful work

**Comment by driver48** [comment]
hi i'm how changeweb access (redirection to HTTPS) ? ı have a same problem? please help me @vmotos

**Comment by DKB3T4** [comment]
Help, I'm having this problem with 4nonimizer, I've tried everything. I reinstalled the program, I used the commands to update the app, but none worked, someone could help me with this message:


[+] There is a problem starting openvpn. Please, check nohup.out for details

Mon Jul 30 15:49:11 2018 WARNING: file 'pass.txt' is group or others accessible
Mon Jul 30 15:49:11 2018 OpenVPN 2.4.5 i686-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar  4 2018
Mon Jul 30 15:49:11 2018 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.08
Mon Jul 30 15:49:11 2018 Error reading username from Auth authfile: pass.txt
Mon Jul 30 15:49:11 2018 Exiting due to fatal error
Mon Jul 30 15:55:22 2018 Unrecognized option or missing or extra parameter(s) in /opt/4nonimizer/vpn/7proxies/7Proxies.com-Lovnic-Romania-renamed.ovpn:15: block-outside-dns (2.4.5)
Mon Jul 30 15:55:22 2018 WARNING: file 'pass.txt' is group or others accessible
Mon Jul 30 15:55:22 2018 OpenVPN 2.4.5 i686-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar  4 2018
Mon Jul 30 15:55:22 2018 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.08
Mon Jul 30 15:55:22 2018 Error reading username from Auth authfile: pass.txt
Mon Jul 30 15:55:22 2018 Exiting due to fatal error

**Comment by frankota** [comment]
Hello I am having the same problem I tryied also to put the credential that I found on the website vpnbook in the file  4nonimizer/vpn/vpnbook/pass.txt but I always have the same problem.
Thanks for the help


`[+] There is a problem starting openvpn. Please, check nohup.out for details

Mon Jul 15 08:47:42 2019 TCP_CLIENT link remote: [AF_INET]198.27.69.198:443
Mon Jul 15 08:47:42 2019 TLS: Initial packet from [AF_INET]198.27.69.198:443, sid=f9a20af1 483fa962
Mon Jul 15 08:47:42 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Jul 15 08:47:42 2019 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Mon Jul 15 08:47:42 2019 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Mon Jul 15 08:47:45 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 1024 bit RSA
Mon Jul 15 08:47:45 2019 [vpnbook.com] Peer Connection Initiated with [AF_INET]198.27.69.198:443
Mon Jul 15 08:47:46 2019 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Mon Jul 15 08:47:46 2019 AUTH: Received control message: AUTH_FAILED
Mon Jul 15 08:47:46 2019 SIGTERM[soft,auth-failure] received, process exiting
Mon Jul 15 08:51:57 2019 WARNING: file 'pass.txt' is group or others accessible
Mon Jul 15 08:51:57 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Mon Jul 15 08:51:57 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Mon Jul 15 08:51:57 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Mon Jul 15 08:51:57 2019 NOTE: --fast-io is disabled since we are not using UDP
Mon Jul 15 08:51:57 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]94.23.57.8:80
Mon Jul 15 08:51:57 2019 Socket Buffers: R=[87380->87380] S=[16384->16384]
Mon Jul 15 08:51:57 2019 Attempting to establish TCP connection with [AF_INET]94.23.57.8:80 [nonblock]
Mon Jul 15 08:51:58 2019 TCP connection established with [AF_INET]94.23.57.8:80
Mon Jul 15 08:51:58 2019 TCP_CLIENT link local: (not bound)
Mon Jul 15 08:51:58 2019 TCP_CLIENT link remote: [AF_INET]94.23.57.8:80
Mon Jul 15 08:51:58 2019 TLS: Initial packet from [AF_INET]94.23.57.8:80, sid=160f79a0 e0815fd4
Mon Jul 15 08:51:58 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Mon Jul 15 08:51:58 2019 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Mon Jul 15 08:51:58 2019 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Mon Jul 15 08:52:00 2019 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 1024 bit RSA
Mon Jul 15 08:52:00 2019 [vpnbook.com] Peer Connection Initiated with [AF_INET]94.23.57.8:80
Mon Jul 15 08:52:02 2019 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Mon Jul 15 08:52:02 2019 AUTH: Received control message: AUTH_FAILED
Mon Jul 15 08:52:02 2019 SIGTERM[soft,auth-failure] received, process exiting
`
