### ISSUE TITLE
There is a problem starting openvpn. Please, check nohup.out for details

### ISSUE THREAD

**Issue by amreos** [Hackplayers/4nonimizer#21]
[+] There is a problem starting openvpn. Please, check nohup.out for details

Thu Jul 13 01:21:02 2017 TCP_CLIENT link local: (not bound)
Thu Jul 13 01:21:02 2017 TCP_CLIENT link remote: [AF_INET]176.126.237.217:80
Thu Jul 13 01:21:02 2017 TLS: Initial packet from [AF_INET]176.126.237.217:80, sid=77f0a2d2 6e6a06a4
Thu Jul 13 01:21:04 2017 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Thu Jul 13 01:21:04 2017 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Thu Jul 13 01:21:08 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 1024 bit RSA
Thu Jul 13 01:21:08 2017 [vpnbook.com] Peer Connection Initiated with [AF_INET]176.126.237.217:80
Thu Jul 13 01:21:10 2017 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Thu Jul 13 01:21:11 2017 AUTH: Received control message: AUTH_FAILED
Thu Jul 13 01:21:11 2017 SIGTERM[soft,auth-failure] received, process exiting
Thu Jul 13 02:02:28 2017 WARNING: file 'pass.txt' is group or others accessible
Thu Jul 13 02:02:28 2017 OpenVPN 2.4.3 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 30 2017
Thu Jul 13 02:02:28 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
Thu Jul 13 02:02:28 2017 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Thu Jul 13 02:02:28 2017 NOTE: --fast-io is disabled since we are not using UDP
Thu Jul 13 02:02:28 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]178.162.193.233:80
Thu Jul 13 02:02:28 2017 Socket Buffers: R=[87380->87380] S=[16384->16384]
Thu Jul 13 02:02:28 2017 Attempting to establish TCP connection with [AF_INET]178.162.193.233:80 [nonblock]
Thu Jul 13 02:02:29 2017 TCP connection established with [AF_INET]178.162.193.233:80
Thu Jul 13 02:02:29 2017 TCP_CLIENT link local: (not bound)
Thu Jul 13 02:02:29 2017 TCP_CLIENT link remote: [AF_INET]178.162.193.233:80
Thu Jul 13 02:02:29 2017 TLS: Initial packet from [AF_INET]178.162.193.233:80, sid=4c3ff9e3 22540d5d
Thu Jul 13 02:02:29 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Jul 13 02:02:30 2017 VERIFY OK: depth=1, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Thu Jul 13 02:02:30 2017 VERIFY OK: depth=0, C=CH, ST=Zurich, L=Zurich, O=vpnbook.com, OU=IT, CN=vpnbook.com, name=vpnbook.com, emailAddress=admin@vpnbook.com
Thu Jul 13 02:02:34 2017 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 1024 bit RSA
Thu Jul 13 02:02:34 2017 [vpnbook.com] Peer Connection Initiated with [AF_INET]178.162.193.233:80
Thu Jul 13 02:02:36 2017 SENT CONTROL [vpnbook.com]: 'PUSH_REQUEST' (status=1)
Thu Jul 13 02:02:36 2017 AUTH: Received control message: AUTH_FAILED
Thu Jul 13 02:02:36 2017 SIGTERM[soft,auth-failure] received, process exiting

**Comment by vmotos** [comment]
Hello,

please execute /opt/4nonimizer/vpn/vpnbook/vpn-get-pass.sh. This issue happens when VPNBook changes its credentials (may be we could always call this script before start function).

I wait your feedback to close the issue.

Regards

**Comment by amreos** [comment]
yes it worked
calling it each time start is a good idea
thank you .

**Comment by pavan123123** [comment]
how to execute that?

**Comment by smainsii** [comment]
hello, 
i have the same issue and i did what you already mentioned but doesn't work, please find bellow the error message.

[+] There is a problem starting openvpn. Please, check nohup.out for details

Sun Aug 12 10:57:43 2018 WARNING: file 'pass.txt' is group or others accessible
Sun Aug 12 10:57:43 2018 OpenVPN 2.4.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar  4 2018
Sun Aug 12 10:57:43 2018 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.08
Sun Aug 12 10:59:13 2018 ERROR: Failed retrieving username or password
Sun Aug 12 10:59:13 2018 Exiting due to fatal error
Sun Aug 12 11:01:06 2018 WARNING: file 'pass.txt' is group or others accessible
Sun Aug 12 11:01:06 2018 OpenVPN 2.4.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar  4 2018
Sun Aug 12 11:01:06 2018 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.08

**Comment by ramesh414** [comment]
@vmotos when i execute /opt/4nonimizer/vpn/vpnbook/vpn-get-pass.sh. this, it asks me credentials which i dont have, any suggestion\?

**Comment by wahyudibayuputra** [comment]
[+] There is a problem starting openvpn. Please, check nohup.out for details

Fri May 24 09:46:58 2019 ERROR: Failed retrieving username or password
Fri May 24 09:46:58 2019 Exiting due to fatal error
Fri May 24 09:48:27 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:48:27 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:48:27 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:49:57 2019 ERROR: Failed retrieving username or password
Fri May 24 09:49:57 2019 Exiting due to fatal error
Fri May 24 09:50:21 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:50:21 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:50:21 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:51:51 2019 ERROR: Failed retrieving username or password
Fri May 24 09:51:51 2019 Exiting due to fatal error
Fri May 24 09:54:48 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:54:48 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:54:48 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:56:18 2019 ERROR: Failed retrieving username or password
Fri May 24 09:56:18 2019 Exiting due to fatal error
Fri May 24 09:56:28 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:56:28 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:56:28 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:57:58 2019 ERROR: Failed retrieving username or password
Fri May 24 09:57:58 2019 Exiting due to fatal error
Fri May 24 09:58:41 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:58:41 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:58:41 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 10:00:11 2019 ERROR: Failed retrieving username or password
Fri May 24 10:00:11 2019 Exiting due to fatal error
Fri May 24 10:20:46 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 10:20:46 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 10:20:46 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10



help me plss, what is this problem ?

**Comment by DaniyalYaseen-ai** [comment]
I am the same problem, although I have followed all above steps. Please help.

[+] There is a problem starting openvpn. Please, check nohup.out for details

Wed Nov 13 13:04:33 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:04:33 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:04:33 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:06:03 2019 ERROR: Failed retrieving username or password
Wed Nov 13 13:06:03 2019 Exiting due to fatal error
Wed Nov 13 13:06:39 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:06:39 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:06:39 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:08:09 2019 ERROR: Failed retrieving username or password
Wed Nov 13 13:08:09 2019 Exiting due to fatal error
Wed Nov 13 13:08:32 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:08:32 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:08:32 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:10:02 2019 ERROR: Failed retrieving username or password
Wed Nov 13 13:10:02 2019 Exiting due to fatal error
Wed Nov 13 13:26:13 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:26:13 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:26:13 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:30:22 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:30:22 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:30:22 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Wed Nov 13 13:31:52 2019 ERROR: Failed retrieving username or password
Wed Nov 13 13:31:52 2019 Exiting due to fatal error
Wed Nov 13 13:47:11 2019 WARNING: file 'pass.txt' is group or others accessible
Wed Nov 13 13:47:11 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Wed Nov 13 13:47:11 2019 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10

root@kali:~/Desktop/4nonimizer#
