### ISSUE TITLE
Problem starting 4nonimizer

### ISSUE THREAD

**Issue by knight304** [Hackplayers/4nonimizer#25]
Hi , I have this problem starting 4nonimizer , I am using Kali linux 2017  

+] Your current IP is ...

[+] Starting 4nonimizer to hide your real IP...

sed: can't read /opt/4nonimizer/vpn/vpnbook/*.ovpn: No such file or directory
ls: cannot access '/opt/4nonimizer/vpn/vpnbook/*.ovpn': No such file or directory
..............................

[+] There is a problem starting openvpn. Please, check nohup.out for details

--pkcs11-pin-cache seconds      : Number of seconds to cache PIN. The default is -1
                                  cache until token is removed.
--pkcs11-id-management          : Acquire identity from management interface.
--pkcs11-id serialized-id 'id'  : Identity to use, get using standalone --show-pkcs11-ids

SSL Library information:
--show-ciphers  : Show cipher algorithms to use with --cipher option.
--show-digests  : Show message digest algorithms to use with --auth option.
--show-engines  : Show hardware crypto accelerator engines (if available).
--show-tls      : Show all TLS ciphers (TLS used only as a control channel).

Generate a random key (only for non-TLS static key encryption mode):
--genkey        : Generate a random key to be used as a shared secret,
                  for use with the --secret option.
--secret file   : Write key to file.

Tun/tap config mode (available with linux 2.4+):
--mktun         : Create a persistent tunnel.
--rmtun         : Remove a persistent tunnel.
--dev tunX|tapX : tun/tap device
--dev-type dt   : Device type.  See tunnel options above for details.
--user user     : User to set privilege to.
--group group   : Group to set privilege to.

PKCS#11 standalone options:
--show-pkcs11-ids provider [cert_private] : Show PKCS#11 available ids.
                                            --verb option can be added *BEFORE* this.

General Standalone Options:
--show-gateway : Show info about default gateway.

What is the problem pls ???

Thnx in advance ;

**Comment by vmotos** [comment]
Execute:
/opt/4nonimizer/vpn/vpnbook/vpn-get-pass.sh 
/opt/4nonimizer/vpn/vpnbook/vpn-get-ovpn.sh 

and tell me if it works.

Rgds

**Comment by vmotos** [comment]
Closed

**Comment by knight304** [comment]
Hi , Im srry i was doing my exam , nd didnt check the thread 

I did the two commands , the first one return nothing the secnd return this : " mv: cannot stat './www.vpnbook.com/free-openvpn-account/*.zip': No such file or directory
unzip:  cannot find or open *.zip, *.zip.zip or *.zip.ZIP.

No zipfiles found. "

any help pls ??

**Comment by knight304** [comment]
Any solutions pls ??

**Comment by vmotos** [comment]
hello, 

first command (vpn-get-pass.sh) should get the free password of user 'vpǹbook' from provider site.
Check if you have installed curl and test:
curl https://www.vpnbook.com/#openvpn 2> /dev/null | grep -E "Password" | awk '{print $2}' | cut -d'<' -f1 | sort -u

second command (vpn-get-ovpn.sh) must download zip file containing al ovpn files. Check if you have installed 'wget' and check:
wget -r -np -l 1 -A zip http://www.vpnbook.com/#openvpn 2> /dev/null

Regards,

**Comment by knight304** [comment]
Hi, thank you for replying i really appreciate your help .

The first command I tried it bring like this :: 

root@kali:~/Desktop/4nonimizer# curl https://www.vpnbook.com/#openvpn 2> /dev/null | grep -E "Password" | awk '{print $2}' | cut -d'<' -f1 | sort -u
root@kali:~/Desktop/4nonimizer# 

The scnd command : 

root@kali:~/Desktop/4nonimizer# wget -r -np -l 1 -A zip http://www.vpnbook.com/#openvpn 2> /dev/null
root@kali:~/Desktop/4nonimizer#

So i think it doesnt work for both !!? any solutions pls ?

**Comment by Armanmd** [comment]
@knight304 _Hello_  **i know how to fix your problem ! if you want my solutions tell me some details !**

**Comment by vmotos** [comment]
You must execute these check commands in install dir: /opt/4nonimizer/vpn/vpnbook. Please check them and send me the response and do an 'ls' to check if the .ovpn files have been downloaded correctly and do 'cat pass.txt' to check if the credentials have been filled.

**Comment by ramesh414** [comment]
vmotos your suggestion helped me, i was able to install 4nonimizer successfully however if i check current ip, its doesnt change. It show the IP of my ISP. Please advice what would be the reason.

**Comment by asif8423** [comment]
[+] Your current IP is 47.8.164.250...


[+] Starting 4nonimizer to hide your real IP...

..............................








[+] There is a problem starting openvpn. Please, check nohup.out for details

what's problem..anyone please help

**Comment by Mknzoof** [comment]
> [+] Your current IP is 47.8.164.250...
> 
> [+] Starting 4nonimizer to hide your real IP...
> 
> ..............................
> 
> [+] There is a problem starting openvpn. Please, check nohup.out for details
> 
> what's problem..anyone please help

+1

**Comment by wahyudibayuputra** [comment]
[+] There is a problem starting openvpn. Please, check nohup.out for details

Fri May 24 09:46:58 2019 ERROR: Failed retrieving username or password
Fri May 24 09:46:58 2019 Exiting due to fatal error
Fri May 24 09:48:27 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:48:27 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:48:27 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:49:57 2019 ERROR: Failed retrieving username or password
Fri May 24 09:49:57 2019 Exiting due to fatal error
Fri May 24 09:50:21 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:50:21 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:50:21 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:51:51 2019 ERROR: Failed retrieving username or password
Fri May 24 09:51:51 2019 Exiting due to fatal error
Fri May 24 09:54:48 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:54:48 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:54:48 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:56:18 2019 ERROR: Failed retrieving username or password
Fri May 24 09:56:18 2019 Exiting due to fatal error
Fri May 24 09:56:28 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:56:28 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:56:28 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 09:57:58 2019 ERROR: Failed retrieving username or password
Fri May 24 09:57:58 2019 Exiting due to fatal error
Fri May 24 09:58:41 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 09:58:41 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 09:58:41 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10
Fri May 24 10:00:11 2019 ERROR: Failed retrieving username or password
Fri May 24 10:00:11 2019 Exiting due to fatal error
Fri May 24 10:20:46 2019 WARNING: file 'pass.txt' is group or others accessible
Fri May 24 10:20:46 2019 OpenVPN 2.4.6 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 30 2018
Fri May 24 10:20:46 2019 library versions: OpenSSL 1.1.1a  20 Nov 2018, LZO 2.10

help me, what is this problem ?

**Comment by DPHoldItDown** [comment]
[+] There is a problem starting openvpn. Please, check nohup.out for details

Tue Aug 13 15:33:53 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]51.68.180.4:53
Tue Aug 13 15:33:53 2019 Socket Buffers: R=[163840->163840] S=[163840->163840]
Tue Aug 13 15:33:53 2019 UDP link local: (not bound)
Tue Aug 13 15:33:53 2019 UDP link remote: [AF_INET]51.68.180.4:53
Tue Aug 13 15:34:53 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Tue Aug 13 15:34:53 2019 TLS Error: TLS handshake failed
Tue Aug 13 15:34:53 2019 SIGUSR1[soft,tls-error] received, process restarting
Tue Aug 13 15:34:53 2019 Restart pause, 5 second(s)
Tue Aug 13 15:34:58 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Tue Aug 13 15:34:59 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]51.68.180.4:53
Tue Aug 13 15:34:59 2019 Socket Buffers: R=[163840->163840] S=[163840->163840]
Tue Aug 13 15:34:59 2019 UDP link local: (not bound)
Tue Aug 13 15:34:59 2019 UDP link remote: [AF_INET]51.68.180.4:53
Tue Aug 13 15:35:44 2019 WARNING: file 'pass.txt' is group or others accessible
Tue Aug 13 15:35:44 2019 OpenVPN 2.4.7 i686-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Tue Aug 13 15:35:44 2019 library versions: OpenSSL 1.1.1b  26 Feb 2019, LZO 2.10
Tue Aug 13 15:35:44 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Tue Aug 13 15:35:44 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]51.68.180.4:53
Tue Aug 13 15:35:44 2019 Socket Buffers: R=[163840->163840] S=[163840->163840]
Tue Aug 13 15:35:44 2019 UDP link local: (not bound)
Tue Aug 13 15:35:44 2019 UDP link remote: [AF_INET]51.68.180.4:53
Tue Aug 13 15:35:59 2019 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Tue Aug 13 15:35:59 2019 TLS Error: TLS handshake failed
Tue Aug 13 15:35:59 2019 SIGUSR1[soft,tls-error] received, process restarting
Tue Aug 13 15:35:59 2019 Restart pause, 5 second(s)
Tue Aug 13 15:36:04 2019 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Tue Aug 13 15:36:04 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]51.68.180.4:53
Tue Aug 13 15:36:04 2019 Socket Buffers: R=[163840->163840] S=[163840->163840]
Tue Aug 13 15:36:04 2019 UDP link local: (not bound)
Tue Aug 13 15:36:04 2019 UDP link remote: [AF_INET]51.68.180.4:53

**Comment by DPHoldItDown** [comment]
i dont know whats the problem here

**Comment by DaniyalYaseen-ai** [comment]
Dear All,
Previous issue has been resolved but now I amgetting below mentioned error. When I run ./4nonimizer start , first it detects my real public IP then gives following output. Someone please help.

[+] There is a problem starting openvpn. Please, check nohup.out for details

Wed Nov 13 14:27:38 2019 Socket Buffers: R=[131072->131072] S=[16384->16384]
Wed Nov 13 14:27:38 2019 Attempting to establish TCP connection with [AF_INET]198.7.62.204:443 [nonblock]
Wed Nov 13 14:27:39 2019 TCP connection established with [AF_INET]198.7.62.204:443
Wed Nov 13 14:27:39 2019 TCP_CLIENT link local: (not bound)
Wed Nov 13 14:27:39 2019 TCP_CLIENT link remote: [AF_INET]198.7.62.204:443
Wed Nov 13 14:27:40 2019 WARNING: No server certificate verification method has been enabled. See http://openvpn.net/howto.html#mitm for more info.
Wed Nov 13 14:27:40 2019 NOTE: --fast-io is disabled since we are not using UDP
Wed Nov 13 14:27:40 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:40 2019 Socket Buffers: R=[131072->131072] S=[16384->16384]
Wed Nov 13 14:27:40 2019 Attempting to establish TCP connection with [AF_INET]198.7.58.147:443 [nonblock]
Wed Nov 13 14:27:41 2019 TCP connection established with [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:41 2019 TCP_CLIENT link local: (not bound)
Wed Nov 13 14:27:41 2019 TCP_CLIENT link remote: [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:42 2019 Connection reset, restarting [-1]
Wed Nov 13 14:27:42 2019 SIGUSR1[soft,connection-reset] received, process restarting
Wed Nov 13 14:27:42 2019 Restart pause, 80 second(s)
Wed Nov 13 14:27:44 2019 Connection reset, restarting [-1]
Wed Nov 13 14:27:44 2019 SIGUSR1[soft,connection-reset] received, process restarting
Wed Nov 13 14:27:44 2019 Restart pause, 5 second(s)
Wed Nov 13 14:27:49 2019 WARNING: No server certificate verification method has been enabled. See http://openvpn.net/howto.html#mitm for more info.
Wed Nov 13 14:27:49 2019 NOTE: --fast-io is disabled since we are not using UDP
Wed Nov 13 14:27:49 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:49 2019 Socket Buffers: R=[131072->131072] S=[16384->16384]
Wed Nov 13 14:27:49 2019 Attempting to establish TCP connection with [AF_INET]198.7.58.147:443 [nonblock]
Wed Nov 13 14:27:50 2019 TCP connection established with [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:50 2019 TCP_CLIENT link local: (not bound)
Wed Nov 13 14:27:50 2019 TCP_CLIENT link remote: [AF_INET]198.7.58.147:443
Wed Nov 13 14:27:52 2019 Connection reset, restarting [-1]
Wed Nov 13 14:27:52 2019 SIGUSR1[soft,connection-reset] received, process restarting
Wed Nov 13 14:27:52 2019 Restart pause, 5 second(s)

**Comment by gainer99** [comment]
Thu Feb 20 06:22:51 2020 WARNING: cannot stat file 'pass.txt': No such file or directory (errno=2)
Options error: --auth-user-pass fails with 'pass.txt': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.
Thu Feb 20 06:37:18 2020 Unrecognized option or missing or extra parameter(s) in /opt/4nonimizer/vpn/7proxies/7proxies.com-freevpn-UnitedStates-renamed.ovpn:19: block-outside-dns (2.4.7)
Thu Feb 20 06:37:18 2020 WARNING: cannot stat file 'pass.txt': No such file or directory (errno=2)
Options error: --auth-user-pass fails with 'pass.txt': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.
Thu Feb 20 06:48:46 2020 Unrecognized option or missing or extra parameter(s) in /opt/4nonimizer/vpn/7proxies/7proxies.com-freevpn-UnitedStates-renamed.ovpn:18: block-outside-dns (2.4.7)
Thu Feb 20 06:48:46 2020 WARNING: cannot stat file 'pass.txt': No such file or directory (errno=2)
Options error: --auth-user-pass fails with 'pass.txt': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.

**Comment by gainer99** [comment]
How to solve this problem?

**Comment by gainer99** [comment]
Sorry
this is full error.

[+] There is a problem starting openvpn. Please, check nohup.out for details

Mon Feb 10 17:08:43 2020 Unrecognized option or missing or extra parameter(s) in /opt/4nonimizer/vpn/7proxies/7proxies.com-freevpn-UnitedStates-renamed.ovpn:18: block-outside-dns (2.4.7)
Mon Feb 10 17:08:43 2020 WARNING: cannot stat file 'pass.txt': No such file or directory (errno=2)
Options error: --auth-user-pass fails with 'pass.txt': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.
Thu Feb 20 02:40:01 2020 Unrecognized option or missing or extra parameter(s) in /opt/4nonimizer/vpn/7proxies/7proxies.com-freevpn-UnitedStates-renamed.ovpn:18: block-outside-dns (2.4.7)
Thu Feb 20 02:40:01 2020 WARNING: cannot stat file 'pass.txt': No such file or directory (errno=2)
Options error: --auth-user-pass fails with 'pass.txt': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.
Thu Feb 20 02:47:48 2020 Unrecognized option or missing or extra parameter(s) in /opt/4nonimizer/vpn/7proxies/7proxies.com-freevpn-UnitedStates-renamed.ovpn:18: block-outside-dns (2.4.7)
Thu Feb 20 02:47:48 2020 WARNING: cannot stat file 'pass.txt': No such file or directory (errno=2)
Options error: --auth-user-pass fails with 'pass.txt': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.
Thu Feb 20 06:22:51 2020 Unrecognized option or missing or extra parameter(s) in /opt/4nonimizer/vpn/7proxies/7proxies.com-freevpn-UnitedStates-renamed.ovpn:18: block-outside-dns (2.4.7)
Thu Feb 20 06:22:51 2020 WARNING: cannot stat file 'pass.txt': No such file or directory (errno=2)
Options error: --auth-user-pass fails with 'pass.txt': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.
Thu Feb 20 06:37:18 2020 Unrecognized option or missing or extra parameter(s) in /opt/4nonimizer/vpn/7proxies/7proxies.com-freevpn-UnitedStates-renamed.ovpn:19: block-outside-dns (2.4.7)
Thu Feb 20 06:37:18 2020 WARNING: cannot stat file 'pass.txt': No such file or directory (errno=2)
Options error: --auth-user-pass fails with 'pass.txt': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.
Thu Feb 20 06:48:46 2020 Unrecognized option or missing or extra parameter(s) in /opt/4nonimizer/vpn/7proxies/7proxies.com-freevpn-UnitedStates-renamed.ovpn:18: block-outside-dns (2.4.7)
Thu Feb 20 06:48:46 2020 WARNING: cannot stat file 'pass.txt': No such file or directory (errno=2)
Options error: --auth-user-pass fails with 'pass.txt': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.

**Comment by dkgmgo** [comment]
when I finished the installation, I executed  4nonimize help and it says command not found!!!! can you help me??
