### ISSUE TITLE
bigbuG 

### ISSUE THREAD

**Issue by Armanmd** [Hackplayers/4nonimizer#31]

**Comment by Armanmd** [comment]
when i want to stop 4nonimizer is buged

OS:Kali Linux 


http://uupload.ir/filelink/BJOAApSF2taS/allm_vid_20171231_144217.mp4

http://uupload.ir/filelink/j1d4KikS3Q5N/80nn_vid_20171231_144505.mp4

**Comment by vmotos** [comment]
links are broken: File not found. ****

**Comment by Armanmd** [comment]
oh no let me upload again

**Comment by Armanmd** [comment]
#**One of my friends made the movie from the desktop**
**_First link:(part 1)_**
<a href="http://uupload.ir/view/tw1g_vid_20171231_144505.mp4" target="_blank"><img src="http://uupload.ir/css/images/udl.png" border="0" alt="First link" /></a>
**_Second link(part 2)_**
<a href="http://uupload.ir/view/4h9r_vid_20171231_144217.mp4" target="_blank"><img src="http://uupload.ir/css/images/udl.png" border="0" alt="Second link" /></a>

`This is a terrible bug‍‍‍‍!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`

**Comment by vmotos** [comment]
Ok, we're going to update Kali to 2017.3 for reproducing the issue and fix it.

**Comment by Armanmd** [comment]
uname -a
Linux Kali 4.14.0-kali1-686-pae #1 SMP Debian 4.14.2-1kali1 (2017-12-04) i686 GNU/Linux

**Comment by vmotos** [comment]
We've already identified and fixed issue.
The problem was that 'stop' funcion did grep 'log-' process and killed it. In last Kali release process table includes:

/usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only

and if you kill it you have the problems that you report.

The version 1.09 has been released. Please, delete manually the directory /opt/4nonimizer, clone the github repo and install again.

I wait your feedback...

**Comment by vmotos** [comment]
Also do 'rm /etc/systemd/system/4non.service' before reinstalling...

**Comment by Armanmd** [comment]
thanks it work very well:P
im so happy.but my isp blocked openvpn i dont khow why :(
im from iran
